// <auto-generated />
namespace HotelBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADDNewCols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDNewCols));
        
        string IMigrationMetadata.Id
        {
            get { return "202110201243413_ADDNewCols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
